### Get test
GET http://localhost:3000/details/3 HTTP/1.1
Host: localhost:3000
Content-Type: application/json


### Post test
POST http://localhost:3000/actor HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "firstName": "Teodoro",
  "lastName": "Cardoso"
}